version: '3.7'

services:
  jloku-api:
    image: localhost:5002/jloku-api
    ports:
      - "5001:5000"
    command: gunicorn --workers 13 --threads 4 --env SCRIPT_NAME=/api --bind 0.0.0.0:5000 --timeout 60 app:app --log-level debug
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: "exit 0"
