version: '3.7'

services:
  jloku-api:
    image: localhost:5002/jloku-api
    ports:
      - "5001:5000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl --fail http://localhost:5000/api/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
