name: deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Remove Previous Docker
      run: docker rm -f jloku-api || true
    - name: Build and Run Docker
      run: docker build -t jloku/jloku-api .  && docker run --name jloku-api -dp 5000:5000 jloku/jloku-api
