name: deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Docker
      run: docker build -t jloku/jloku-api . && docker run -dp 5000:5000 jloku/jloku-api
